name: Lint and Format

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm ci || npm install
        working-directory: frontend

      - name: Lint + Format frontend
        run: |
          npx eslint . --fix
          npx prettier . --check
        working-directory: frontend

      - name: Install backend dependencies
        run: npm ci || npm install
        working-directory: backend

      - name: Lint + Format backend
        run: |
          npx eslint . --fix
          npx prettier . --check
        working-directory: backend
